version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=ibrohim
    ports:
      - 8000:8000

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=spotifytwo
      - POSTGRES_USER=ibrohim
      - POSTGRES_PASSWORD=qwaszx11
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
