# Generated by Django 3.2.3 on 2021-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='movie', to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, related_name='actor', to='movie.Actor'),
        ),
    ]
