# Generated by Django 3.2.3 on 2021-06-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_actor_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FileField(upload_to='movies/'),
        ),
    ]
