# Generated by Django 3.2.3 on 2021-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FileField(blank=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
    ]
