# Generated by Django 2.0.7 on 2021-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20210620_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
