# Generated by Django 2.0.7 on 2021-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
