# Generated by Django 3.2.4 on 2021-08-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20210629_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='movie_comment', to='movie.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_id', to='movie.movie'),
        ),
    ]
